networkingLevel1:
  testSshNotOpenFromInternet: True
  testRdpNotOpenFromInternet: True

iamLevel1:
  testMfaEnabledForConsoleUsers: True
  testUnusedCredentialsAreDeactivated: True
  testAccessKeysAreRotated: True